I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 15, in script call
    call start_world
  File "game/rpg_world/world_screen.rpy", line 5, in script call
    call screen world_walk
  File "game/rpg_npc/npc_talk.rpy", line 17, in script call
    call start_world
  File "game/rpg_world/world_screen.rpy", line 5, in script call
    call screen world_walk
  File "game/rpg_npc/npc_talk.rpy", line 17, in script call
    call start_world
  File "game/rpg_world/world_screen.rpy", line 5, in script call
    call screen world_walk
  File "game/rpg_npc/npc_talk.rpy", line 17, in script call
    call start_world
  File "game/rpg_world/world_screen.rpy", line 5, in script call
    call screen world_walk
  File "game/rpg_npc/npc_talk.rpy", line 17, in script call
    call start_world
  File "game/rpg_world/world_screen.rpy", line 5, in script call
    call screen world_walk
  File "game/rpg_npc/npc_talk.rpy", line 17, in script call
    call start_world
  File "game/rpg_world/world_screen.rpy", line 5, in script call
    call screen world_walk
  File "game/rpg_npc/npc_talk.rpy", line 17, in script call
    call start_world
  File "game/rpg_world/world_screen.rpy", line 5, in script call
    call screen world_walk
  File "game/rpg_npc/npc_talk.rpy", line 17, in script call
    call start_world
  File "game/rpg_world/world_screen.rpy", line 5, in script call
    call screen world_walk
  File "game/rpg_npc/npc_talk.rpy", line 17, in script call
    call start_world
  File "game/rpg_world/world_screen.rpy", line 5, in script call
    call screen world_walk
  File "game/rpg_npc/npc_talk.rpy", line 11, in script call
    call expression story_label pass (story_controller.get_story(story_label),npc)
  File "game/rpg_story/main_queen_labels.rpy", line 191, in script
    $ dungeon_controller.start(5)
  File "game/rpg_story/main_queen_labels.rpy", line 191, in <module>
    $ dungeon_controller.start(5)
AttributeError: 'NoneType' object has no attribute 'card'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 15, in script call
    call start_world
  File "game/rpg_world/world_screen.rpy", line 5, in script call
    call screen world_walk
  File "game/rpg_npc/npc_talk.rpy", line 17, in script call
    call start_world
  File "game/rpg_world/world_screen.rpy", line 5, in script call
    call screen world_walk
  File "game/rpg_npc/npc_talk.rpy", line 17, in script call
    call start_world
  File "game/rpg_world/world_screen.rpy", line 5, in script call
    call screen world_walk
  File "game/rpg_npc/npc_talk.rpy", line 17, in script call
    call start_world
  File "game/rpg_world/world_screen.rpy", line 5, in script call
    call screen world_walk
  File "game/rpg_npc/npc_talk.rpy", line 17, in script call
    call start_world
  File "game/rpg_world/world_screen.rpy", line 5, in script call
    call screen world_walk
  File "game/rpg_npc/npc_talk.rpy", line 17, in script call
    call start_world
  File "game/rpg_world/world_screen.rpy", line 5, in script call
    call screen world_walk
  File "game/rpg_npc/npc_talk.rpy", line 17, in script call
    call start_world
  File "game/rpg_world/world_screen.rpy", line 5, in script call
    call screen world_walk
  File "game/rpg_npc/npc_talk.rpy", line 17, in script call
    call start_world
  File "game/rpg_world/world_screen.rpy", line 5, in script call
    call screen world_walk
  File "game/rpg_npc/npc_talk.rpy", line 17, in script call
    call start_world
  File "game/rpg_world/world_screen.rpy", line 5, in script call
    call screen world_walk
  File "game/rpg_npc/npc_talk.rpy", line 11, in script call
    call expression story_label pass (story_controller.get_story(story_label),npc)
  File "game/rpg_story/main_queen_labels.rpy", line 191, in script
    $ dungeon_controller.start(5)
  File "/home/wooyme/renpy-8.2.1-sdk/renpy/ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/wooyme/renpy-8.2.1-sdk/renpy/python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/rpg_story/main_queen_labels.rpy", line 191, in <module>
    $ dungeon_controller.start(5)
  File "game/rpg_dungeon/dungeon_controller_ren.py", line 52, in start
    self.step()
  File "game/rpg_dungeon/dungeon_controller_ren.py", line 79, in step
    self.player_hands.append(enemy.card())
AttributeError: 'NoneType' object has no attribute 'card'

Linux-6.5.0-35-generic-x86_64-with-glibc2.35 x86_64
Ren'Py 8.2.1.24030407
Android GUI 1.31
Mon May 20 17:46:00 2024
