I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 15, in script
    $ world_controller.start_game()
  File "game/script.rpy", line 15, in <module>
    $ world_controller.start_game()
ValueError: Sample larger than population or is negative

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 15, in script
    $ world_controller.start_game()
  File "/home/wooyme/renpy-8.2.1-sdk/renpy/ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/wooyme/renpy-8.2.1-sdk/renpy/python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 15, in <module>
    $ world_controller.start_game()
  File "game/rpg_world/world_controller_ren.py", line 30, in start_game
    actions = random.sample(THEME_LOVE_LIBRARY, 20)
  File "lib/python3.9/random.py", line 449, in sample
ValueError: Sample larger than population or is negative

Linux-6.5.0-35-generic-x86_64-with-glibc2.35 x86_64
Ren'Py 8.2.1.24030407
Android GUI 1.31
Mon May 27 16:35:27 2024
